apiVersion: v1
kind: Secret
metadata:
  annotations:
  name: {{ include "infinispan.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "infinispan.name" . }}
    helm.sh/chart: {{ include "infinispan.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  {{- if .Values.application.password }}
  application-password: {{ .Values.application.password }}
  {{- else }}
  application-password: {{ randAlphaNum 16 }}
  {{- end }}
  {{- if .Values.application.user }}
  application-user: {{ .Values.application.user }}
  {{- else }}
  application-user: {{ randAlphaNum 16 }}
  {{- end }}
