apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
{{ include "mychart.app" . | indent 4}}
data:
  myvalue: "Hello World"
  {{- $relname := .Release.Name -}}
    {{- range $key, $val := .Values.favorite }}
      {{ $key }}: {{ $val | quote }}
    {{- end }}
  release: {{ $relname }}
  toppings: |-
    {{- range $index, $topping := .Values.pizzaToppings }}
      {{ $index }}: {{ $topping }}
  {{- end }}
{{ include "mychart.app" . | indent 2}}
  {{- $files := .Files }}
  {{- range tuple "config1.toml" "config2.toml" "config3.toml" }}
    {{ . }}: |- {{ $files.Get . }}
  {{- end }}
  token: |-
    {{ .Files.Get "config1.toml" | b64enc }}